export const AREAS = [
  { id: 1, name: "Poli Melati, Parkir Lt.2 & 3, PU, Lapangan Parkir Belakang" },
  { id: 2, name: "Halaman, Taman Wings, Taman Herbal" },
  { id: 3, name: "Halaman, Taman Wings, Taman Herbal, PU (Landscape)" },
  { id: 4, name: "Staff Quarter & SQ Lt.1" },
  { id: 5, name: "Gedung Admin" },
  { id: 6, name: "Anggrek Eksekutif Lt.1" },
  { id: 7, name: "Anggrek Eksekutif M2" },
  { id: 8, name: "Dental, IT" },
  { id: 9, name: "Lobby, Gedung Entrance & Endoscopy, Toilet Umum Lobby, Registrasi, Poli Lt.1" },
  { id: 10, name: "Farmasi Lt.1, Logistik, Lift Kuning & Koridor Lt.1, Laundry & Kitchen, Koridor Belakang" },
  { id: 11, name: "Radiologi, Forensik, CR" },
  { id: 12, name: "IGD Lt.1 & 2" },
  { id: 13, name: "Energy Center, Parkir Dokter Spesialis, IPAL" },
  { id: 14, name: "Poli Seluruh Lt.2, CSSD, Lab, Gudang Farmasi" },
  { id: 15, name: "COT" },
  { id: 16, name: "ICU, NS All & Koridor Belakang, HD, Pain Clinic, Koridor Tengah, Toilet Umum, ODC" },
  { id: 17, name: "Lt.5 & VK" },
  { id: 18, name: "Lt.6" },
  { id: 19, name: "Lt.10" },
  { id: 20, name: "Lt.11" },
  { id: 21, name: "Lt.12" },
  { id: 22, name: "Lt.13" },
  { id: 23, name: "Lt.14" },
];

export const SHIFTS = [
  { code: "NS", name: "Non Shift", jam: "07.00 - 16.00", keterangan: "Jadwal standar reguler." },
  { code: "NS 2", name: "Non Shift 2", jam: "11.00 - 20.00", keterangan: "Jadwal siang hingga malam." },
  { code: "MD", name: "Shift Middle", jam: "10.00 - 18.00", keterangan: "Jadwal tengah hari." },
  { code: "MD 2", name: "Shift Middle 2", jam: "12.00 - 20.00", keterangan: "Jadwal siang hingga malam." },
  { code: "P", name: "Shift Pagi", jam: "06.00 - 14.00", keterangan: "Shift paling awal untuk persiapan area." },
  { code: "S", name: "Shift Siang", jam: "14.00 - 22.00", keterangan: "Melanjutkan operasional siang ke malam." },
  { code: "M", name: "Shift Malam", jam: "22.00 - 06.00", keterangan: "Penjagaan dan pembersihan area malam hari." },
  { code: "L", name: "Lepas & Libur", jam: "-", keterangan: "Petugas sedang tidak bertugas." },
  { code: "P1", name: "Halaman 1", jam: "07.00 - 15.00", keterangan: "Fokus pada pembersihan area luar/halaman." },
  { code: "P2", name: "Halaman 2", jam: "07.00 - 12.00", keterangan: "Shift halaman dengan durasi lebih singkat." },
];
