export const STOK_BARANG_ITEMS = [
  { id: 1, nama: "Hitam 40", satuan: "Lembar" },
  { id: 2, nama: "Hitam 60", satuan: "Lembar" },
  { id: 3, nama: "Hitam 90", satuan: "Lembar" },
  { id: 4, nama: "Kuning 40", satuan: "Lembar" },
  { id: 5, nama: "Kuning 60", satuan: "Lembar" },
  { id: 6, nama: "Kuning 90", satuan: "Lembar" },
  { id: 7, nama: "Ungu 40", satuan: "Lembar" },
  { id: 8, nama: "Ungu 60", satuan: "Lembar" },
  { id: 9, nama: "Coklat 40", satuan: "Lembar" },
  { id: 10, nama: "Coklat 60", satuan: "Lembar" },
  { id: 11, nama: "Hand Towel", satuan: "Pack" },
  { id: 12, nama: "Hand Soap (Calmic)", satuan: "Botol" },
  { id: 13, nama: "Tisu Roll", satuan: "Roll" },
  { id: 14, nama: "Safety Box Jerigen 5 L", satuan: "Pcs" },
  { id: 15, nama: "Safety Box Kontainer 5 L", satuan: "Pcs" },
  { id: 16, nama: "Safety Box Kontainer 1 L", satuan: "Pcs" },
  { id: 17, nama: "Floor Cleaner", satuan: "Liter" },
  { id: 18, nama: "Karbol", satuan: "Liter" },
  { id: 19, nama: "Bowl Getter", satuan: "Botol" },
  { id: 20, nama: "Detergent Boom", satuan: "Kg" },
  { id: 21, nama: "Pengharum Toilet/Stella", satuan: "Pcs" },
  { id: 22, nama: "Tapas Hijau", satuan: "Pcs" },
  { id: 23, nama: "Kuas", satuan: "Pcs" },
  { id: 24, nama: "Kape", satuan: "Pcs" },
  { id: 25, nama: "Sprayer", satuan: "Pcs" },
  { id: 26, nama: "Nilon Broom", satuan: "Pcs" },
  { id: 27, nama: "Broom set Dustpan mini", satuan: "Set" },
  { id: 28, nama: "Lobby Duster", satuan: "Pcs" },
  { id: 29, nama: "Tissue Facial (Wajah)", satuan: "Box" },
  { id: 30, nama: "Refill Looby", satuan: "Pcs" },
  { id: 31, nama: "Refill Mop Kuning", satuan: "Pcs" },
  { id: 32, nama: "Refill Mop Merah", satuan: "Pcs" },
  { id: 33, nama: "Refill Mop Hijau", satuan: "Pcs" },
  { id: 34, nama: "Refill Mop Biru", satuan: "Pcs" },
  { id: 35, nama: "Lap Micro Fiber Merah", satuan: "Pcs" },
  { id: 36, nama: "Lap Micro Fiber Kuning", satuan: "Pcs" },
  { id: 37, nama: "Lap Micro Fiber Hijau", satuan: "Pcs" },
  { id: 38, nama: "Lap Micro Fiber Biru", satuan: "Pcs" },
  { id: 39, nama: "Disinfektan H2O2", satuan: "Liter" },
];
