export const STOK_BARANG_ITEMS = [
  { id: 1, nama: "Hitam 40" },
  { id: 2, nama: "Hitam 60" },
  { id: 3, nama: "Hitam 90" },
  { id: 4, nama: "Kuning 40" },
  { id: 5, nama: "Kuning 60" },
  { id: 6, nama: "Kuning 90" },
  { id: 7, nama: "Ungu 40" },
  { id: 8, nama: "Ungu 60" },
  { id: 9, nama: "Coklat 40" },
  { id: 10, nama: "Coklat 60" },
  { id: 11, nama: "Hand Towel" },
  { id: 12, nama: "Hand Soap (Calmic)" },
  { id: 13, nama: "Tisu Roll" },
  { id: 14, nama: "Safety Box Jerigen 5 L" },
  { id: 15, nama: "Safety Box Kontainer 5 L" },
  { id: 16, nama: "Safety Box Kontainer 1 L" },
  { id: 17, nama: "Floor Cleaner" },
  { id: 18, nama: "Karbol" },
  { id: 19, nama: "Bowl Getter" },
  { id: 20, nama: "Detergent Boom" },
  { id: 21, nama: "Pengharum Toilet/Stella" },
  { id: 22, nama: "Tapas Hijau" },
  { id: 23, nama: "Kuas" },
  { id: 24, nama: "Kape" },
  { id: 25, nama: "Sprayer" },
  { id: 26, nama: "Nilon Broom" },
  { id: 27, nama: "Broom set Dustpan mini" },
  { id: 28, nama: "Lobby Duster" },
  { id: 29, nama: "Tissue Facial (Wajah)" },
  { id: 30, nama: "Refill Looby" },
  { id: 31, nama: "Refill Mop Kuning" },
  { id: 32, nama: "Refill Mop Merah" },
  { id: 33, nama: "Refill Mop Hijau" },
  { id: 34, nama: "Refill Mop Biru" },
  { id: 35, nama: "Lap Micro Fiber Merah" },
  { id: 36, nama: "Lap Micro Fiber Kuning" },
  { id: 37, nama: "Lap Micro Fiber Hijau" },
  { id: 38, nama: "Lap Micro Fiber Biru" },
  { id: 39, nama: "Disinfektan H2O2" },
];
